spring:
  profiles:
    include: prop

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: WARN
    org.hibernate.type.descriptor.sql: trace
    org.springframework.boot.devtools.restart: ERROR
    org.springframework.security.web.DefaultSecurityFilterChain: ERROR
